name: depot
description: Depot is a Dart actor model state management library intended for use with the Flutter apps.
version: 0.0.2
homepage: https://github.com/eyevox/depot

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  rxdart: ^0.27.5
  dartdoc: ^6.1.1
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
